### PR TITLE
convert robot/teamdomain with hyphens into underscores for env var lookup

### PR DESCRIPTION
**Pull request by drnic**

### CODE REVIEW

**Comment by trinchan** [comment]
So this is for the case when you have a robot or team name with hyphens in their name? I'm not sure I like this change, as it complicates the already kinda convoluted way of using env vars.

`team-name` -> `TEAM-NAME_IN_TOKEN`
`team-name` -> `TEAM_NAME_IN_TOKEN`

The benefits don't warrant the change in my opinion, but if you are passionate about it, or maybe if someone else could chime in with their thoughts, I would reconsider it.

**Comment by drnic** [comment]
I don't think hyphens are valid for env vars




Or at least direnv yelled at me for trying to use hyphens. Which led to the patch.

**Comment by drnic** [comment]
I'll keep the patch in my aggregate merged branch that I'm running as I need it; but I understand if you don't want to merge. Just wanted to share something that that I needed.

**Comment by trinchan** [comment]
You are correct. Also I see that variables cannot start with a numeral. This will cause some issues for teams/robots. We'll need to think about a solution

**Pull request closed without merging**
