### PR TITLE
Add support for sending to Payload.ResponseUrl

### PR DESCRIPTION
**Pull request by 9len**
This change adds support for sending a response to a slash command using the ResponseUrl in the Payload.

* Introduce Message type, with IncomingWebHook and SlashCommandResponse as alias types
* Add private sendToUrl method to Message. 
* Rewrite IncomingWebHook.Send to use Message.sendToUrl
* Add SlashCommandResponse.Send(Payload), which sends to the ResponseUrl in the Payload.
* Update README and example code (I didn't go crazy here, just left a breadcrumb in the DeferredAction comments).
* Incidentally remote some trailing whitespace. My editor does this, let me know if you want me to revert that to make the diff cleaner

I tested this with my bot, was able to send both to an incoming web hook and to the ResponseUrl.

### CODE REVIEW

**Comment by 9len** [comment]
ping? I have this working in several of my bots, but would like to avoid hand-patched vendored code. if there's a different way you'd like me to do it, please let me know. thanks!

**Comment by trinchan** [comment]
looks good. again, thanks for the contribution! the parameter `urlType` doesn't seem to be used except in the error messages. i think the type of url will be clear in the log because we are logging the url as well. what do you think about removing it to clean it up a bit?

**Comment by 9len** [comment]
Yeah, I added urlType to maintain logging compatibility, but if that's not important, I'm happy to remove it.

**Comment by 9len** [comment]
OK, removed urlType and added an explicit error message for empty responseUrl. The empty check in sendToUrl is no longer strictly necessary, but guards against a future caller failing to check.

**Comment by 9len** [comment]
This is ready to go. Would you prefer that I rebase the two changes into one, or can you merge as is?

Thanks!

**Comment by trinchan** [comment]
Thanks for your contribution!

**Pull request merged**
